#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiFirm.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="taxiserver")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["taxiserverConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addDriver")]
		public int addDriver([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> health, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> license_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id, health, license_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateNoticeContentByID")]
		public void updateNoticeContentByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> notice_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NText")] string content)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), notice_id, title, content);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addEmpolyee")]
		public int addEmpolyee([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> firm_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(20)")] string id_card, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> birthday, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> gender, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string telephone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string empolyee_address)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), password, firm_id, name, id_card, birthday, gender, telephone, empolyee_address);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addHost")]
		public int addHost([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string photo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id, photo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addInvoice")]
		public int addInvoice([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> amount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), amount);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addManager")]
		public int addManager([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addNews")]
		public int addNews([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NText")] string content, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(256)")] string picture_path)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), title, empolyee_id, content, picture_path);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addNotice")]
		public int addNotice([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NText")] string content)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), title, empolyee_id, content);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteEmpolyeeById")]
		public int deleteEmpolyeeById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteHostById")]
		public int deleteHostById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteManagerById")]
		public int deleteManagerById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteNewsByID")]
		public int deleteNewsByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> news_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), news_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteNoticeByID")]
		public int deleteNoticeByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> notice_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), notice_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.grantManager")]
		public void grantManager([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string position)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id, position);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.registInvoiceToCustomer")]
		public int registInvoiceToCustomer([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> invoice_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> customer_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), invoice_id, customer_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.revokeManager")]
		public void revokeManager([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.setDriverHealth")]
		public int setDriverHealth([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> health)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id, health);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.setHostPhoto")]
		public int setHostPhoto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string photo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id, photo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.setManagerPosition")]
		public void setManagerPosition([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string position)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id, position);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.setNewsPicturePathByID")]
		public int setNewsPicturePathByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> news_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(256)")] string picture_path)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), news_id, picture_path);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateEmpolyeeById")]
		public int updateEmpolyeeById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> gender, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string telephone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string address)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id, name, gender, telephone, address);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateEmpolyeePassword")]
		public int updateEmpolyeePassword([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id, password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateNewsContentByID")]
		public void updateNewsContentByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> news_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NText")] string content)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), news_id, title, content);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.checkCustomerLoginPassword", IsComposable=true)]
		public System.Nullable<int> checkCustomerLoginPassword([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> customer_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string password)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customer_id, password).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.isManager", IsComposable=true)]
		public System.Nullable<int> isManager([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.checkEmpolyeeLoginPassword", IsComposable=true)]
		public System.Nullable<int> checkEmpolyeeLoginPassword([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string password)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id, password).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllFirm", IsComposable=true)]
		public IQueryable<getAllFirmResult> getAllFirm()
		{
			return this.CreateMethodCallQuery<getAllFirmResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllHost", IsComposable=true)]
		public IQueryable<getAllHostResult> getAllHost()
		{
			return this.CreateMethodCallQuery<getAllHostResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllNews", IsComposable=true)]
		public IQueryable<getAllNewsResult> getAllNews()
		{
			return this.CreateMethodCallQuery<getAllNewsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllNotice", IsComposable=true)]
		public IQueryable<getAllNoticeResult> getAllNotice()
		{
			return this.CreateMethodCallQuery<getAllNoticeResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllOrder", IsComposable=true)]
		public IQueryable<getAllOrderResult> getAllOrder()
		{
			return this.CreateMethodCallQuery<getAllOrderResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getCurrentOrder", IsComposable=true)]
		public IQueryable<getCurrentOrderResult> getCurrentOrder()
		{
			return this.CreateMethodCallQuery<getCurrentOrderResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getDriverByPage", IsComposable=true)]
		public IQueryable<getDriverByPageResult> getDriverByPage([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize)
		{
			return this.CreateMethodCallQuery<getDriverByPageResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageNumber, pageSize);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getDriverPageCount", IsComposable=true)]
		public System.Nullable<int> getDriverPageCount([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageSize).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getEmpolyeeById", IsComposable=true)]
		public IQueryable<getEmpolyeeByIdResult> getEmpolyeeById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id)
		{
			return this.CreateMethodCallQuery<getEmpolyeeByIdResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getEmpolyeeIdByIdCard", IsComposable=true)]
		public System.Nullable<int> getEmpolyeeIdByIdCard([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(20)")] string id_card)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_card).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getHostById", IsComposable=true)]
		public IQueryable<getHostByIdResult> getHostById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id)
		{
			return this.CreateMethodCallQuery<getHostByIdResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getHostByPage", IsComposable=true)]
		public IQueryable<getHostByPageResult> getHostByPage([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize)
		{
			return this.CreateMethodCallQuery<getHostByPageResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageNumber, pageSize);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getHostPageCount", IsComposable=true)]
		public System.Nullable<int> getHostPageCount([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageSize).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getNewsByID", IsComposable=true)]
		public IQueryable<getNewsByIDResult> getNewsByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> news_id)
		{
			return this.CreateMethodCallQuery<getNewsByIDResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), news_id);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getNewsByPage", IsComposable=true)]
		public IQueryable<getNewsByPageResult> getNewsByPage([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize)
		{
			return this.CreateMethodCallQuery<getNewsByPageResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageNumber, pageSize);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getNewsPageCount", IsComposable=true)]
		public System.Nullable<int> getNewsPageCount([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageSize).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getNoticeByID", IsComposable=true)]
		public IQueryable<getNoticeByIDResult> getNoticeByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> notice_id)
		{
			return this.CreateMethodCallQuery<getNoticeByIDResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), notice_id);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getNoticeByPage", IsComposable=true)]
		public IQueryable<getNoticeByPageResult> getNoticeByPage([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize)
		{
			return this.CreateMethodCallQuery<getNoticeByPageResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageNumber, pageSize);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getNoticePageCount", IsComposable=true)]
		public System.Nullable<int> getNoticePageCount([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageSize).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getTaxiByOwnerEmpolyeeId", IsComposable=true)]
		public IQueryable<getTaxiByOwnerEmpolyeeIdResult> getTaxiByOwnerEmpolyeeId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id)
		{
			return this.CreateMethodCallQuery<getTaxiByOwnerEmpolyeeIdResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getTaxiByPlateNumber", IsComposable=true)]
		public IQueryable<getTaxiByPlateNumberResult> getTaxiByPlateNumber([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string plate_number)
		{
			return this.CreateMethodCallQuery<getTaxiByPlateNumberResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), plate_number);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getTaxiHostInformation", IsComposable=true)]
		public IQueryable<getTaxiHostInformationResult> getTaxiHostInformation()
		{
			return this.CreateMethodCallQuery<getTaxiHostInformationResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.isDriver", IsComposable=true)]
		public System.Nullable<int> isDriver([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.isEmpolyee", IsComposable=true)]
		public System.Nullable<int> isEmpolyee([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.isHost", IsComposable=true)]
		public System.Nullable<int> isHost([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empolyee_id)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empolyee_id).ReturnValue));
		}
	}
	
	public partial class getAllFirmResult
	{
		
		private int _firm_id;
		
		private string _firm_name;
		
		private string _address;
		
		private string _phone_number;
		
		public getAllFirmResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_id", DbType="Int NOT NULL")]
		public int firm_id
		{
			get
			{
				return this._firm_id;
			}
			set
			{
				if ((this._firm_id != value))
				{
					this._firm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string firm_name
		{
			get
			{
				return this._firm_name;
			}
			set
			{
				if ((this._firm_name != value))
				{
					this._firm_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this._phone_number = value;
				}
			}
		}
	}
	
	public partial class getAllHostResult
	{
		
		private int _empolyee_id;
		
		private string _name;
		
		private string _id_card;
		
		private System.DateTime _birthday;
		
		private System.Nullable<bool> _gender;
		
		private string _telephone;
		
		private string _photo;
		
		private int _firm_id;
		
		private string _firm_name;
		
		private string _phone_number;
		
		private string _empolyee_address;
		
		private string _firm_address;
		
		public getAllHostResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_id", DbType="Int NOT NULL")]
		public int empolyee_id
		{
			get
			{
				return this._empolyee_id;
			}
			set
			{
				if ((this._empolyee_id != value))
				{
					this._empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_card", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string id_card
		{
			get
			{
				return this._id_card;
			}
			set
			{
				if ((this._id_card != value))
				{
					this._id_card = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date NOT NULL")]
		public System.DateTime birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this._birthday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Bit")]
		public System.Nullable<bool> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this._telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo", DbType="NVarChar(200)")]
		public string photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this._photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_id", DbType="Int NOT NULL")]
		public int firm_id
		{
			get
			{
				return this._firm_id;
			}
			set
			{
				if ((this._firm_id != value))
				{
					this._firm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string firm_name
		{
			get
			{
				return this._firm_name;
			}
			set
			{
				if ((this._firm_name != value))
				{
					this._firm_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this._phone_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string empolyee_address
		{
			get
			{
				return this._empolyee_address;
			}
			set
			{
				if ((this._empolyee_address != value))
				{
					this._empolyee_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string firm_address
		{
			get
			{
				return this._firm_address;
			}
			set
			{
				if ((this._firm_address != value))
				{
					this._firm_address = value;
				}
			}
		}
	}
	
	public partial class getAllNewsResult
	{
		
		private int _news_id;
		
		private string _title;
		
		private System.Nullable<int> _empolyee_id;
		
		private string _name;
		
		private System.DateTime _publish_time;
		
		private string _picture_path;
		
		private string _content;
		
		public getAllNewsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_id", DbType="Int NOT NULL")]
		public int news_id
		{
			get
			{
				return this._news_id;
			}
			set
			{
				if ((this._news_id != value))
				{
					this._news_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_id", DbType="Int")]
		public System.Nullable<int> empolyee_id
		{
			get
			{
				return this._empolyee_id;
			}
			set
			{
				if ((this._empolyee_id != value))
				{
					this._empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publish_time", DbType="SmallDateTime NOT NULL")]
		public System.DateTime publish_time
		{
			get
			{
				return this._publish_time;
			}
			set
			{
				if ((this._publish_time != value))
				{
					this._publish_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picture_path", DbType="NVarChar(256)")]
		public string picture_path
		{
			get
			{
				return this._picture_path;
			}
			set
			{
				if ((this._picture_path != value))
				{
					this._picture_path = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this._content = value;
				}
			}
		}
	}
	
	public partial class getAllNoticeResult
	{
		
		private int _notice_id;
		
		private string _title;
		
		private System.Nullable<int> _empolyee_id;
		
		private string _name;
		
		private System.DateTime _publish_time;
		
		private string _content;
		
		public getAllNoticeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notice_id", DbType="Int NOT NULL")]
		public int notice_id
		{
			get
			{
				return this._notice_id;
			}
			set
			{
				if ((this._notice_id != value))
				{
					this._notice_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_id", DbType="Int")]
		public System.Nullable<int> empolyee_id
		{
			get
			{
				return this._empolyee_id;
			}
			set
			{
				if ((this._empolyee_id != value))
				{
					this._empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publish_time", DbType="Date NOT NULL")]
		public System.DateTime publish_time
		{
			get
			{
				return this._publish_time;
			}
			set
			{
				if ((this._publish_time != value))
				{
					this._publish_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this._content = value;
				}
			}
		}
	}
	
	public partial class getAllOrderResult
	{
		
		private int _order_id;
		
		private string _plate_number;
		
		private int _empolyee_id;
		
		private System.DateTime _rent_begin_time;
		
		private System.DateTime _rent_due_return_time;
		
		private System.Nullable<System.DateTime> _rent_return_time;
		
		private string _taxi_color;
		
		private string _taxi_brand;
		
		private bool _is_available;
		
		private System.Nullable<int> _owner_firm_id;
		
		private System.Nullable<int> _owner_empolyee_id;
		
		private string _name;
		
		private string _id_card;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private System.Nullable<bool> _gender;
		
		private string _telephone;
		
		private System.Nullable<int> _age;
		
		private System.Nullable<int> _health;
		
		private System.Nullable<int> _firm_id;
		
		private string _firm_name;
		
		private string _firm_address;
		
		private string _phone_number;
		
		private string _license_id;
		
		private System.Nullable<System.DateTime> _license_time;
		
		private string _photo_path;
		
		private string _empolyee_address;
		
		public getAllOrderResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int NOT NULL")]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this._order_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plate_number", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string plate_number
		{
			get
			{
				return this._plate_number;
			}
			set
			{
				if ((this._plate_number != value))
				{
					this._plate_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_id", DbType="Int NOT NULL")]
		public int empolyee_id
		{
			get
			{
				return this._empolyee_id;
			}
			set
			{
				if ((this._empolyee_id != value))
				{
					this._empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rent_begin_time", DbType="Date NOT NULL")]
		public System.DateTime rent_begin_time
		{
			get
			{
				return this._rent_begin_time;
			}
			set
			{
				if ((this._rent_begin_time != value))
				{
					this._rent_begin_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rent_due_return_time", DbType="Date NOT NULL")]
		public System.DateTime rent_due_return_time
		{
			get
			{
				return this._rent_due_return_time;
			}
			set
			{
				if ((this._rent_due_return_time != value))
				{
					this._rent_due_return_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rent_return_time", DbType="Date")]
		public System.Nullable<System.DateTime> rent_return_time
		{
			get
			{
				return this._rent_return_time;
			}
			set
			{
				if ((this._rent_return_time != value))
				{
					this._rent_return_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxi_color", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string taxi_color
		{
			get
			{
				return this._taxi_color;
			}
			set
			{
				if ((this._taxi_color != value))
				{
					this._taxi_color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxi_brand", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string taxi_brand
		{
			get
			{
				return this._taxi_brand;
			}
			set
			{
				if ((this._taxi_brand != value))
				{
					this._taxi_brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_available", DbType="Bit NOT NULL")]
		public bool is_available
		{
			get
			{
				return this._is_available;
			}
			set
			{
				if ((this._is_available != value))
				{
					this._is_available = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_firm_id", DbType="Int")]
		public System.Nullable<int> owner_firm_id
		{
			get
			{
				return this._owner_firm_id;
			}
			set
			{
				if ((this._owner_firm_id != value))
				{
					this._owner_firm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_empolyee_id", DbType="Int")]
		public System.Nullable<int> owner_empolyee_id
		{
			get
			{
				return this._owner_empolyee_id;
			}
			set
			{
				if ((this._owner_empolyee_id != value))
				{
					this._owner_empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_card", DbType="Char(20)")]
		public string id_card
		{
			get
			{
				return this._id_card;
			}
			set
			{
				if ((this._id_card != value))
				{
					this._id_card = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this._birthday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Bit")]
		public System.Nullable<bool> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="VarChar(20)")]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this._telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_health", DbType="Int")]
		public System.Nullable<int> health
		{
			get
			{
				return this._health;
			}
			set
			{
				if ((this._health != value))
				{
					this._health = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_id", DbType="Int")]
		public System.Nullable<int> firm_id
		{
			get
			{
				return this._firm_id;
			}
			set
			{
				if ((this._firm_id != value))
				{
					this._firm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_name", DbType="NVarChar(20)")]
		public string firm_name
		{
			get
			{
				return this._firm_name;
			}
			set
			{
				if ((this._firm_name != value))
				{
					this._firm_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_address", DbType="NVarChar(50)")]
		public string firm_address
		{
			get
			{
				return this._firm_address;
			}
			set
			{
				if ((this._firm_address != value))
				{
					this._firm_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(20)")]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this._phone_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_license_id", DbType="VarChar(50)")]
		public string license_id
		{
			get
			{
				return this._license_id;
			}
			set
			{
				if ((this._license_id != value))
				{
					this._license_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_license_time", DbType="Date")]
		public System.Nullable<System.DateTime> license_time
		{
			get
			{
				return this._license_time;
			}
			set
			{
				if ((this._license_time != value))
				{
					this._license_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo_path", DbType="NVarChar(256)")]
		public string photo_path
		{
			get
			{
				return this._photo_path;
			}
			set
			{
				if ((this._photo_path != value))
				{
					this._photo_path = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_address", DbType="NVarChar(50)")]
		public string empolyee_address
		{
			get
			{
				return this._empolyee_address;
			}
			set
			{
				if ((this._empolyee_address != value))
				{
					this._empolyee_address = value;
				}
			}
		}
	}
	
	public partial class getCurrentOrderResult
	{
		
		private int _order_id;
		
		private string _plate_number;
		
		private int _empolyee_id;
		
		private System.DateTime _rent_begin_time;
		
		private System.DateTime _rent_due_return_time;
		
		private System.Nullable<System.DateTime> _rent_return_time;
		
		private string _taxi_color;
		
		private string _taxi_brand;
		
		private bool _is_available;
		
		private System.Nullable<int> _owner_firm_id;
		
		private System.Nullable<int> _owner_empolyee_id;
		
		private string _name;
		
		private string _id_card;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private System.Nullable<bool> _gender;
		
		private string _telephone;
		
		private System.Nullable<int> _age;
		
		private System.Nullable<int> _health;
		
		private System.Nullable<int> _firm_id;
		
		private string _firm_name;
		
		private string _firm_address;
		
		private string _phone_number;
		
		private string _license_id;
		
		private System.Nullable<System.DateTime> _license_time;
		
		private string _photo_path;
		
		private string _empolyee_address;
		
		public getCurrentOrderResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int NOT NULL")]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this._order_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plate_number", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string plate_number
		{
			get
			{
				return this._plate_number;
			}
			set
			{
				if ((this._plate_number != value))
				{
					this._plate_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_id", DbType="Int NOT NULL")]
		public int empolyee_id
		{
			get
			{
				return this._empolyee_id;
			}
			set
			{
				if ((this._empolyee_id != value))
				{
					this._empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rent_begin_time", DbType="Date NOT NULL")]
		public System.DateTime rent_begin_time
		{
			get
			{
				return this._rent_begin_time;
			}
			set
			{
				if ((this._rent_begin_time != value))
				{
					this._rent_begin_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rent_due_return_time", DbType="Date NOT NULL")]
		public System.DateTime rent_due_return_time
		{
			get
			{
				return this._rent_due_return_time;
			}
			set
			{
				if ((this._rent_due_return_time != value))
				{
					this._rent_due_return_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rent_return_time", DbType="Date")]
		public System.Nullable<System.DateTime> rent_return_time
		{
			get
			{
				return this._rent_return_time;
			}
			set
			{
				if ((this._rent_return_time != value))
				{
					this._rent_return_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxi_color", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string taxi_color
		{
			get
			{
				return this._taxi_color;
			}
			set
			{
				if ((this._taxi_color != value))
				{
					this._taxi_color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxi_brand", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string taxi_brand
		{
			get
			{
				return this._taxi_brand;
			}
			set
			{
				if ((this._taxi_brand != value))
				{
					this._taxi_brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_available", DbType="Bit NOT NULL")]
		public bool is_available
		{
			get
			{
				return this._is_available;
			}
			set
			{
				if ((this._is_available != value))
				{
					this._is_available = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_firm_id", DbType="Int")]
		public System.Nullable<int> owner_firm_id
		{
			get
			{
				return this._owner_firm_id;
			}
			set
			{
				if ((this._owner_firm_id != value))
				{
					this._owner_firm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_empolyee_id", DbType="Int")]
		public System.Nullable<int> owner_empolyee_id
		{
			get
			{
				return this._owner_empolyee_id;
			}
			set
			{
				if ((this._owner_empolyee_id != value))
				{
					this._owner_empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_card", DbType="Char(20)")]
		public string id_card
		{
			get
			{
				return this._id_card;
			}
			set
			{
				if ((this._id_card != value))
				{
					this._id_card = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this._birthday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Bit")]
		public System.Nullable<bool> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="VarChar(20)")]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this._telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_health", DbType="Int")]
		public System.Nullable<int> health
		{
			get
			{
				return this._health;
			}
			set
			{
				if ((this._health != value))
				{
					this._health = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_id", DbType="Int")]
		public System.Nullable<int> firm_id
		{
			get
			{
				return this._firm_id;
			}
			set
			{
				if ((this._firm_id != value))
				{
					this._firm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_name", DbType="NVarChar(20)")]
		public string firm_name
		{
			get
			{
				return this._firm_name;
			}
			set
			{
				if ((this._firm_name != value))
				{
					this._firm_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_address", DbType="NVarChar(50)")]
		public string firm_address
		{
			get
			{
				return this._firm_address;
			}
			set
			{
				if ((this._firm_address != value))
				{
					this._firm_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(20)")]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this._phone_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_license_id", DbType="VarChar(50)")]
		public string license_id
		{
			get
			{
				return this._license_id;
			}
			set
			{
				if ((this._license_id != value))
				{
					this._license_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_license_time", DbType="Date")]
		public System.Nullable<System.DateTime> license_time
		{
			get
			{
				return this._license_time;
			}
			set
			{
				if ((this._license_time != value))
				{
					this._license_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo_path", DbType="NVarChar(256)")]
		public string photo_path
		{
			get
			{
				return this._photo_path;
			}
			set
			{
				if ((this._photo_path != value))
				{
					this._photo_path = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_address", DbType="NVarChar(50)")]
		public string empolyee_address
		{
			get
			{
				return this._empolyee_address;
			}
			set
			{
				if ((this._empolyee_address != value))
				{
					this._empolyee_address = value;
				}
			}
		}
	}
	
	public partial class getDriverByPageResult
	{
		
		private System.Nullable<long> _rowNum;
		
		private int _empolyee_id;
		
		private string _name;
		
		private string _id_card;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private System.Nullable<bool> _gender;
		
		private string _telephone;
		
		private System.Nullable<int> _age;
		
		private System.Nullable<int> _health;
		
		private System.Nullable<int> _firm_id;
		
		private string _firm_name;
		
		private string _phone_number;
		
		private string _license_id;
		
		private System.Nullable<System.DateTime> _license_time;
		
		private string _photo_path;
		
		private string _firm_address;
		
		private string _empolyee_address;
		
		public getDriverByPageResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowNum", DbType="BigInt")]
		public System.Nullable<long> rowNum
		{
			get
			{
				return this._rowNum;
			}
			set
			{
				if ((this._rowNum != value))
				{
					this._rowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_id", DbType="Int NOT NULL")]
		public int empolyee_id
		{
			get
			{
				return this._empolyee_id;
			}
			set
			{
				if ((this._empolyee_id != value))
				{
					this._empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_card", DbType="Char(20)")]
		public string id_card
		{
			get
			{
				return this._id_card;
			}
			set
			{
				if ((this._id_card != value))
				{
					this._id_card = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this._birthday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Bit")]
		public System.Nullable<bool> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="VarChar(20)")]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this._telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_health", DbType="Int")]
		public System.Nullable<int> health
		{
			get
			{
				return this._health;
			}
			set
			{
				if ((this._health != value))
				{
					this._health = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_id", DbType="Int")]
		public System.Nullable<int> firm_id
		{
			get
			{
				return this._firm_id;
			}
			set
			{
				if ((this._firm_id != value))
				{
					this._firm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_name", DbType="NVarChar(20)")]
		public string firm_name
		{
			get
			{
				return this._firm_name;
			}
			set
			{
				if ((this._firm_name != value))
				{
					this._firm_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(20)")]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this._phone_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_license_id", DbType="VarChar(50)")]
		public string license_id
		{
			get
			{
				return this._license_id;
			}
			set
			{
				if ((this._license_id != value))
				{
					this._license_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_license_time", DbType="Date")]
		public System.Nullable<System.DateTime> license_time
		{
			get
			{
				return this._license_time;
			}
			set
			{
				if ((this._license_time != value))
				{
					this._license_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo_path", DbType="NVarChar(256)")]
		public string photo_path
		{
			get
			{
				return this._photo_path;
			}
			set
			{
				if ((this._photo_path != value))
				{
					this._photo_path = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_address", DbType="NVarChar(50)")]
		public string firm_address
		{
			get
			{
				return this._firm_address;
			}
			set
			{
				if ((this._firm_address != value))
				{
					this._firm_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_address", DbType="NVarChar(50)")]
		public string empolyee_address
		{
			get
			{
				return this._empolyee_address;
			}
			set
			{
				if ((this._empolyee_address != value))
				{
					this._empolyee_address = value;
				}
			}
		}
	}
	
	public partial class getEmpolyeeByIdResult
	{
		
		private int _empolyee_id;
		
		private int _firm_id;
		
		private string _name;
		
		private string _id_card;
		
		private System.DateTime _birthday;
		
		private System.Nullable<bool> _gender;
		
		private string _telephone;
		
		private System.Nullable<int> _age;
		
		private string _empolyee_address;
		
		public getEmpolyeeByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_id", DbType="Int NOT NULL")]
		public int empolyee_id
		{
			get
			{
				return this._empolyee_id;
			}
			set
			{
				if ((this._empolyee_id != value))
				{
					this._empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_id", DbType="Int NOT NULL")]
		public int firm_id
		{
			get
			{
				return this._firm_id;
			}
			set
			{
				if ((this._firm_id != value))
				{
					this._firm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_card", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string id_card
		{
			get
			{
				return this._id_card;
			}
			set
			{
				if ((this._id_card != value))
				{
					this._id_card = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date NOT NULL")]
		public System.DateTime birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this._birthday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Bit")]
		public System.Nullable<bool> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this._telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string empolyee_address
		{
			get
			{
				return this._empolyee_address;
			}
			set
			{
				if ((this._empolyee_address != value))
				{
					this._empolyee_address = value;
				}
			}
		}
	}
	
	public partial class getHostByIdResult
	{
		
		private int _empolyee_id;
		
		private string _name;
		
		private string _id_card;
		
		private System.DateTime _birthday;
		
		private System.Nullable<bool> _gender;
		
		private string _telephone;
		
		private string _address;
		
		private string _photo;
		
		private int _firm_id;
		
		private string _firm_name;
		
		private string _firm_address;
		
		private string _phone_number;
		
		public getHostByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_id", DbType="Int NOT NULL")]
		public int empolyee_id
		{
			get
			{
				return this._empolyee_id;
			}
			set
			{
				if ((this._empolyee_id != value))
				{
					this._empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_card", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string id_card
		{
			get
			{
				return this._id_card;
			}
			set
			{
				if ((this._id_card != value))
				{
					this._id_card = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date NOT NULL")]
		public System.DateTime birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this._birthday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Bit")]
		public System.Nullable<bool> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this._telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo", DbType="NVarChar(200)")]
		public string photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this._photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_id", DbType="Int NOT NULL")]
		public int firm_id
		{
			get
			{
				return this._firm_id;
			}
			set
			{
				if ((this._firm_id != value))
				{
					this._firm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string firm_name
		{
			get
			{
				return this._firm_name;
			}
			set
			{
				if ((this._firm_name != value))
				{
					this._firm_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string firm_address
		{
			get
			{
				return this._firm_address;
			}
			set
			{
				if ((this._firm_address != value))
				{
					this._firm_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this._phone_number = value;
				}
			}
		}
	}
	
	public partial class getHostByPageResult
	{
		
		private System.Nullable<long> _rowNum;
		
		private int _empolyee_id;
		
		private string _name;
		
		private string _id_card;
		
		private System.DateTime _birthday;
		
		private System.Nullable<bool> _gender;
		
		private string _telephone;
		
		private string _address;
		
		private string _photo;
		
		private int _firm_id;
		
		private string _firm_name;
		
		private string _firm_address;
		
		private string _phone_number;
		
		public getHostByPageResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowNum", DbType="BigInt")]
		public System.Nullable<long> rowNum
		{
			get
			{
				return this._rowNum;
			}
			set
			{
				if ((this._rowNum != value))
				{
					this._rowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_id", DbType="Int NOT NULL")]
		public int empolyee_id
		{
			get
			{
				return this._empolyee_id;
			}
			set
			{
				if ((this._empolyee_id != value))
				{
					this._empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_card", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string id_card
		{
			get
			{
				return this._id_card;
			}
			set
			{
				if ((this._id_card != value))
				{
					this._id_card = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date NOT NULL")]
		public System.DateTime birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this._birthday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Bit")]
		public System.Nullable<bool> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this._telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo", DbType="NVarChar(200)")]
		public string photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this._photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_id", DbType="Int NOT NULL")]
		public int firm_id
		{
			get
			{
				return this._firm_id;
			}
			set
			{
				if ((this._firm_id != value))
				{
					this._firm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string firm_name
		{
			get
			{
				return this._firm_name;
			}
			set
			{
				if ((this._firm_name != value))
				{
					this._firm_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string firm_address
		{
			get
			{
				return this._firm_address;
			}
			set
			{
				if ((this._firm_address != value))
				{
					this._firm_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this._phone_number = value;
				}
			}
		}
	}
	
	public partial class getNewsByIDResult
	{
		
		private System.Nullable<int> _news_id;
		
		private string _title;
		
		private System.Nullable<int> _empolyee_id;
		
		private string _name;
		
		private System.Nullable<System.DateTime> _publish_time;
		
		private string _picture_path;
		
		private string _content;
		
		public getNewsByIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_id", DbType="Int")]
		public System.Nullable<int> news_id
		{
			get
			{
				return this._news_id;
			}
			set
			{
				if ((this._news_id != value))
				{
					this._news_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_id", DbType="Int")]
		public System.Nullable<int> empolyee_id
		{
			get
			{
				return this._empolyee_id;
			}
			set
			{
				if ((this._empolyee_id != value))
				{
					this._empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publish_time", DbType="Date")]
		public System.Nullable<System.DateTime> publish_time
		{
			get
			{
				return this._publish_time;
			}
			set
			{
				if ((this._publish_time != value))
				{
					this._publish_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picture_path", DbType="NVarChar(256)")]
		public string picture_path
		{
			get
			{
				return this._picture_path;
			}
			set
			{
				if ((this._picture_path != value))
				{
					this._picture_path = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this._content = value;
				}
			}
		}
	}
	
	public partial class getNewsByPageResult
	{
		
		private System.Nullable<long> _rowNum;
		
		private int _news_id;
		
		private string _title;
		
		private System.Nullable<int> _empolyee_id;
		
		private System.DateTime _publish_time;
		
		private string _picture_path;
		
		private string _content;
		
		private string _name;
		
		public getNewsByPageResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowNum", DbType="BigInt")]
		public System.Nullable<long> rowNum
		{
			get
			{
				return this._rowNum;
			}
			set
			{
				if ((this._rowNum != value))
				{
					this._rowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_id", DbType="Int NOT NULL")]
		public int news_id
		{
			get
			{
				return this._news_id;
			}
			set
			{
				if ((this._news_id != value))
				{
					this._news_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_id", DbType="Int")]
		public System.Nullable<int> empolyee_id
		{
			get
			{
				return this._empolyee_id;
			}
			set
			{
				if ((this._empolyee_id != value))
				{
					this._empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publish_time", DbType="SmallDateTime NOT NULL")]
		public System.DateTime publish_time
		{
			get
			{
				return this._publish_time;
			}
			set
			{
				if ((this._publish_time != value))
				{
					this._publish_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picture_path", DbType="NVarChar(256)")]
		public string picture_path
		{
			get
			{
				return this._picture_path;
			}
			set
			{
				if ((this._picture_path != value))
				{
					this._picture_path = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this._content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
	}
	
	public partial class getNoticeByIDResult
	{
		
		private int _notice_id;
		
		private string _title;
		
		private System.Nullable<int> _empolyee_id;
		
		private string _name;
		
		private System.DateTime _publish_time;
		
		private string _content;
		
		public getNoticeByIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notice_id", DbType="Int NOT NULL")]
		public int notice_id
		{
			get
			{
				return this._notice_id;
			}
			set
			{
				if ((this._notice_id != value))
				{
					this._notice_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_id", DbType="Int")]
		public System.Nullable<int> empolyee_id
		{
			get
			{
				return this._empolyee_id;
			}
			set
			{
				if ((this._empolyee_id != value))
				{
					this._empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publish_time", DbType="SmallDateTime NOT NULL")]
		public System.DateTime publish_time
		{
			get
			{
				return this._publish_time;
			}
			set
			{
				if ((this._publish_time != value))
				{
					this._publish_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this._content = value;
				}
			}
		}
	}
	
	public partial class getNoticeByPageResult
	{
		
		private System.Nullable<long> _rowNum;
		
		private int _notice_id;
		
		private string _title;
		
		private System.Nullable<int> _empolyee_id;
		
		private System.DateTime _publish_time;
		
		private string _content;
		
		private string _name;
		
		public getNoticeByPageResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowNum", DbType="BigInt")]
		public System.Nullable<long> rowNum
		{
			get
			{
				return this._rowNum;
			}
			set
			{
				if ((this._rowNum != value))
				{
					this._rowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notice_id", DbType="Int NOT NULL")]
		public int notice_id
		{
			get
			{
				return this._notice_id;
			}
			set
			{
				if ((this._notice_id != value))
				{
					this._notice_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_id", DbType="Int")]
		public System.Nullable<int> empolyee_id
		{
			get
			{
				return this._empolyee_id;
			}
			set
			{
				if ((this._empolyee_id != value))
				{
					this._empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publish_time", DbType="SmallDateTime NOT NULL")]
		public System.DateTime publish_time
		{
			get
			{
				return this._publish_time;
			}
			set
			{
				if ((this._publish_time != value))
				{
					this._publish_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this._content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
	}
	
	public partial class getTaxiByOwnerEmpolyeeIdResult
	{
		
		private string _plate_number;
		
		private string _taxi_color;
		
		private string _taxi_brand;
		
		private bool _is_available;
		
		private System.Nullable<int> _owner_firm_id;
		
		private System.Nullable<int> _owner_empolyee_id;
		
		public getTaxiByOwnerEmpolyeeIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plate_number", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string plate_number
		{
			get
			{
				return this._plate_number;
			}
			set
			{
				if ((this._plate_number != value))
				{
					this._plate_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxi_color", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string taxi_color
		{
			get
			{
				return this._taxi_color;
			}
			set
			{
				if ((this._taxi_color != value))
				{
					this._taxi_color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxi_brand", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string taxi_brand
		{
			get
			{
				return this._taxi_brand;
			}
			set
			{
				if ((this._taxi_brand != value))
				{
					this._taxi_brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_available", DbType="Bit NOT NULL")]
		public bool is_available
		{
			get
			{
				return this._is_available;
			}
			set
			{
				if ((this._is_available != value))
				{
					this._is_available = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_firm_id", DbType="Int")]
		public System.Nullable<int> owner_firm_id
		{
			get
			{
				return this._owner_firm_id;
			}
			set
			{
				if ((this._owner_firm_id != value))
				{
					this._owner_firm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_empolyee_id", DbType="Int")]
		public System.Nullable<int> owner_empolyee_id
		{
			get
			{
				return this._owner_empolyee_id;
			}
			set
			{
				if ((this._owner_empolyee_id != value))
				{
					this._owner_empolyee_id = value;
				}
			}
		}
	}
	
	public partial class getTaxiByPlateNumberResult
	{
		
		private string _taxi_color;
		
		private string _taxi_brand;
		
		private bool _is_available;
		
		private System.Nullable<int> _owner_empolyee_id;
		
		private string _name;
		
		private string _id_card;
		
		private System.DateTime _birthday;
		
		private System.Nullable<bool> _gender;
		
		private string _telephone;
		
		private string _photo;
		
		private int _firm_id;
		
		private string _firm_name;
		
		private string _phone_number;
		
		private string _empolyee_address;
		
		private string _firm_address;
		
		private string _plate_number;
		
		public getTaxiByPlateNumberResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxi_color", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string taxi_color
		{
			get
			{
				return this._taxi_color;
			}
			set
			{
				if ((this._taxi_color != value))
				{
					this._taxi_color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxi_brand", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string taxi_brand
		{
			get
			{
				return this._taxi_brand;
			}
			set
			{
				if ((this._taxi_brand != value))
				{
					this._taxi_brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_available", DbType="Bit NOT NULL")]
		public bool is_available
		{
			get
			{
				return this._is_available;
			}
			set
			{
				if ((this._is_available != value))
				{
					this._is_available = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_empolyee_id", DbType="Int")]
		public System.Nullable<int> owner_empolyee_id
		{
			get
			{
				return this._owner_empolyee_id;
			}
			set
			{
				if ((this._owner_empolyee_id != value))
				{
					this._owner_empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_card", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string id_card
		{
			get
			{
				return this._id_card;
			}
			set
			{
				if ((this._id_card != value))
				{
					this._id_card = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date NOT NULL")]
		public System.DateTime birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this._birthday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Bit")]
		public System.Nullable<bool> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this._telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo", DbType="NVarChar(200)")]
		public string photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this._photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_id", DbType="Int NOT NULL")]
		public int firm_id
		{
			get
			{
				return this._firm_id;
			}
			set
			{
				if ((this._firm_id != value))
				{
					this._firm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string firm_name
		{
			get
			{
				return this._firm_name;
			}
			set
			{
				if ((this._firm_name != value))
				{
					this._firm_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this._phone_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string empolyee_address
		{
			get
			{
				return this._empolyee_address;
			}
			set
			{
				if ((this._empolyee_address != value))
				{
					this._empolyee_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string firm_address
		{
			get
			{
				return this._firm_address;
			}
			set
			{
				if ((this._firm_address != value))
				{
					this._firm_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plate_number", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string plate_number
		{
			get
			{
				return this._plate_number;
			}
			set
			{
				if ((this._plate_number != value))
				{
					this._plate_number = value;
				}
			}
		}
	}
	
	public partial class getTaxiHostInformationResult
	{
		
		private string _plate_number;
		
		private string _taxi_color;
		
		private string _taxi_brand;
		
		private bool _is_available;
		
		private System.Nullable<int> _owner_empolyee_id;
		
		private string _name;
		
		private string _id_card;
		
		private System.DateTime _birthday;
		
		private System.Nullable<bool> _gender;
		
		private string _telephone;
		
		private string _photo;
		
		private int _firm_id;
		
		private string _firm_name;
		
		private string _phone_number;
		
		private string _empolyee_address;
		
		private string _firm_address;
		
		public getTaxiHostInformationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plate_number", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string plate_number
		{
			get
			{
				return this._plate_number;
			}
			set
			{
				if ((this._plate_number != value))
				{
					this._plate_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxi_color", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string taxi_color
		{
			get
			{
				return this._taxi_color;
			}
			set
			{
				if ((this._taxi_color != value))
				{
					this._taxi_color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxi_brand", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string taxi_brand
		{
			get
			{
				return this._taxi_brand;
			}
			set
			{
				if ((this._taxi_brand != value))
				{
					this._taxi_brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_available", DbType="Bit NOT NULL")]
		public bool is_available
		{
			get
			{
				return this._is_available;
			}
			set
			{
				if ((this._is_available != value))
				{
					this._is_available = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_empolyee_id", DbType="Int")]
		public System.Nullable<int> owner_empolyee_id
		{
			get
			{
				return this._owner_empolyee_id;
			}
			set
			{
				if ((this._owner_empolyee_id != value))
				{
					this._owner_empolyee_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_card", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string id_card
		{
			get
			{
				return this._id_card;
			}
			set
			{
				if ((this._id_card != value))
				{
					this._id_card = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date NOT NULL")]
		public System.DateTime birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this._birthday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Bit")]
		public System.Nullable<bool> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this._telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo", DbType="NVarChar(200)")]
		public string photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this._photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_id", DbType="Int NOT NULL")]
		public int firm_id
		{
			get
			{
				return this._firm_id;
			}
			set
			{
				if ((this._firm_id != value))
				{
					this._firm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string firm_name
		{
			get
			{
				return this._firm_name;
			}
			set
			{
				if ((this._firm_name != value))
				{
					this._firm_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this._phone_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empolyee_address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string empolyee_address
		{
			get
			{
				return this._empolyee_address;
			}
			set
			{
				if ((this._empolyee_address != value))
				{
					this._empolyee_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firm_address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string firm_address
		{
			get
			{
				return this._firm_address;
			}
			set
			{
				if ((this._firm_address != value))
				{
					this._firm_address = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
