<?xml version="1.0" encoding="utf-8"?><Database Name="taxiserver" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.60.36.5;Initial Catalog=taxiserver;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="taxiserverConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.checkCustomerLoginPassword" Method="checkCustomerLoginPassword" IsComposable="true">
    <Parameter Name="customer_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.checkEmpolyeeLoginPassword" Method="checkEmpolyeeLoginPassword" IsComposable="true">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getAllFirm" Method="getAllFirm" IsComposable="true">
    <ElementType Name="getAllFirmResult">
      <Column Name="firm_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firm_name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="firm_address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getAllFirmView" Method="getAllFirmView" IsComposable="true">
    <ElementType Name="getAllFirmViewResult">
      <Column Name="firm_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firm_name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="firm_address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="empolyee_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="driver_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="host_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="manager_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="taxi_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getCustomerInvoicePageCount" Method="getCustomerInvoicePageCount" IsComposable="true">
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="customer_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getCustomerInvoiceByPage" Method="getCustomerInvoiceByPage" IsComposable="true">
    <Parameter Name="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="customer_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="getCustomerInvoiceByPageResult">
      <Column Name="rowNum" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nick_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="credit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="invoice_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="create_time" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="regist_time" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getCustomerByPage" Method="getCustomerByPage" IsComposable="true">
    <Parameter Name="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <ElementType Name="getCustomerByPageResult">
      <Column Name="rowNum" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nick_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="credit" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getCustomerById" Method="getCustomerById" IsComposable="true">
    <Parameter Name="customer_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="getCustomerByIdResult">
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nick_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="credit" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getCustomePageCount" Method="getCustomePageCount" IsComposable="true">
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getEmpolyeeById" Method="getEmpolyeeById" IsComposable="true">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="getEmpolyeeByIdResult">
      <Column Name="empolyee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firm_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_card" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="empolyee_address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getFirmByID" Method="getFirmByID" IsComposable="true">
    <Parameter Name="firm_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="getFirmByIDResult">
      <Column Name="firm_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firm_name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="firm_address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getFirmViewByPage" Method="getFirmViewByPage" IsComposable="true">
    <Parameter Name="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <ElementType Name="getFirmViewByPageResult">
      <Column Name="rowNum" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="firm_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firm_name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="firm_address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="empolyee_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="driver_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="host_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="manager_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="taxi_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getFirmViewPageCount" Method="getFirmViewPageCount" IsComposable="true">
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.isDriver" Method="isDriver" IsComposable="true">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.isEmpolyee" Method="isEmpolyee" IsComposable="true">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.isHost" Method="isHost" IsComposable="true">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.isManager" Method="isManager" IsComposable="true">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getManagerByPage" Method="getManagerByPage" IsComposable="true">
    <Parameter Name="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <ElementType Name="getManagerByPageResult">
      <Column Name="rowNum" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="empolyee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id_card" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="firm_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="firm_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="empolyee_address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="firm_address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getManagerPageCount" Method="getManagerPageCount" IsComposable="true">
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addDriver" Method="addDriver">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="health" Type="System.Int32" DbType="Int" />
    <Parameter Name="license_id" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addEmpolyee" Method="addEmpolyee">
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="firm_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="id_card" Type="System.String" DbType="Char(20)" />
    <Parameter Name="birthday" Type="System.DateTime" DbType="Date" />
    <Parameter Name="gender" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="telephone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="empolyee_address" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>