<?xml version="1.0" encoding="utf-8"?><Database Name="taxiserver" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.60.36.5;Initial Catalog=taxiserver;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="taxiserverConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.addDriver" Method="addDriver">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="health" Type="System.Int32" DbType="Int" />
    <Parameter Name="license_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateNoticeContentByID" Method="updateNoticeContentByID">
    <Parameter Name="notice_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="title" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="content" Type="System.String" DbType="NText" />
  </Function>
  <Function Name="dbo.addEmpolyee" Method="addEmpolyee">
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="firm_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="id_card" Type="System.String" DbType="Char(20)" />
    <Parameter Name="birthday" Type="System.DateTime" DbType="Date" />
    <Parameter Name="gender" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="telephone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="empolyee_address" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addHost" Method="addHost">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="photo" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addInvoice" Method="addInvoice">
    <Parameter Name="amount" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addManager" Method="addManager">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addNews" Method="addNews">
    <Parameter Name="title" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="content" Type="System.String" DbType="NText" />
    <Parameter Name="picture_path" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addNotice" Method="addNotice">
    <Parameter Name="title" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="content" Type="System.String" DbType="NText" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteEmpolyeeById" Method="deleteEmpolyeeById">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteHostById" Method="deleteHostById">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteManagerById" Method="deleteManagerById">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteNewsByID" Method="deleteNewsByID">
    <Parameter Name="news_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteNoticeByID" Method="deleteNoticeByID">
    <Parameter Name="notice_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.grantManager" Method="grantManager">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="position" Type="System.String" DbType="NVarChar(20)" />
  </Function>
  <Function Name="dbo.registInvoiceToCustomer" Method="registInvoiceToCustomer">
    <Parameter Name="invoice_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="customer_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.revokeManager" Method="revokeManager">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
  </Function>
  <Function Name="dbo.setDriverHealth" Method="setDriverHealth">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="health" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.setHostPhoto" Method="setHostPhoto">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="photo" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.setManagerPosition" Method="setManagerPosition">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="position" Type="System.String" DbType="NVarChar(20)" />
  </Function>
  <Function Name="dbo.setNewsPicturePathByID" Method="setNewsPicturePathByID">
    <Parameter Name="news_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="picture_path" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateEmpolyeeById" Method="updateEmpolyeeById">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gender" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="telephone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="address" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateEmpolyeePassword" Method="updateEmpolyeePassword">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateNewsContentByID" Method="updateNewsContentByID">
    <Parameter Name="news_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="title" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="content" Type="System.String" DbType="NText" />
  </Function>
  <Function Name="dbo.checkCustomerLoginPassword" Method="checkCustomerLoginPassword" IsComposable="true">
    <Parameter Name="customer_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.isManager" Method="isManager" IsComposable="true">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.checkEmpolyeeLoginPassword" Method="checkEmpolyeeLoginPassword" IsComposable="true">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getAllFirm" Method="getAllFirm" IsComposable="true">
    <ElementType Name="getAllFirmResult">
      <Column Name="firm_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firm_name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getAllHost" Method="getAllHost" IsComposable="true">
    <ElementType Name="getAllHostResult">
      <Column Name="empolyee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_card" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="photo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="firm_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firm_name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="empolyee_address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="firm_address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getAllNews" Method="getAllNews" IsComposable="true">
    <ElementType Name="getAllNewsResult">
      <Column Name="news_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="empolyee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="publish_time" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="picture_path" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="content" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.getAllNotice" Method="getAllNotice" IsComposable="true">
    <ElementType Name="getAllNoticeResult">
      <Column Name="notice_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="empolyee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="publish_time" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.getAllOrder" Method="getAllOrder" IsComposable="true">
    <ElementType Name="getAllOrderResult">
      <Column Name="order_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="plate_number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="empolyee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rent_begin_time" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="rent_due_return_time" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="rent_return_time" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="taxi_color" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="taxi_brand" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="is_available" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="owner_firm_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="owner_empolyee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id_card" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="health" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="firm_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="firm_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="firm_address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="license_id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="license_time" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="photo_path" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="empolyee_address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getCurrentOrder" Method="getCurrentOrder" IsComposable="true">
    <ElementType Name="getCurrentOrderResult">
      <Column Name="order_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="plate_number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="empolyee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rent_begin_time" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="rent_due_return_time" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="rent_return_time" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="taxi_color" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="taxi_brand" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="is_available" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="owner_firm_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="owner_empolyee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id_card" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="health" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="firm_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="firm_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="firm_address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="license_id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="license_time" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="photo_path" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="empolyee_address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getDriverByPage" Method="getDriverByPage" IsComposable="true">
    <Parameter Name="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <ElementType Name="getDriverByPageResult">
      <Column Name="rowNum" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="empolyee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id_card" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="health" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="firm_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="firm_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="license_id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="license_time" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="photo_path" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="firm_address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="empolyee_address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getDriverPageCount" Method="getDriverPageCount" IsComposable="true">
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getEmpolyeeById" Method="getEmpolyeeById" IsComposable="true">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="getEmpolyeeByIdResult">
      <Column Name="empolyee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firm_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_card" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="empolyee_address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getEmpolyeeIdByIdCard" Method="getEmpolyeeIdByIdCard" IsComposable="true">
    <Parameter Name="id_card" Type="System.String" DbType="Char(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getHostById" Method="getHostById" IsComposable="true">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="getHostByIdResult">
      <Column Name="empolyee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_card" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="photo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="firm_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firm_name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="firm_address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getHostByPage" Method="getHostByPage" IsComposable="true">
    <Parameter Name="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <ElementType Name="getHostByPageResult">
      <Column Name="rowNum" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="empolyee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_card" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="photo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="firm_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firm_name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="firm_address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getHostPageCount" Method="getHostPageCount" IsComposable="true">
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getNewsByID" Method="getNewsByID" IsComposable="true">
    <Parameter Name="news_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="getNewsByIDResult">
      <Column Name="news_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="empolyee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="publish_time" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="picture_path" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="content" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.getNewsByPage" Method="getNewsByPage" IsComposable="true">
    <Parameter Name="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <ElementType Name="getNewsByPageResult">
      <Column Name="rowNum" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="news_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="empolyee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="publish_time" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="picture_path" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="content" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getNewsPageCount" Method="getNewsPageCount" IsComposable="true">
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getNoticeByID" Method="getNoticeByID" IsComposable="true">
    <Parameter Name="notice_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="getNoticeByIDResult">
      <Column Name="notice_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="empolyee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="publish_time" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.getNoticeByPage" Method="getNoticeByPage" IsComposable="true">
    <Parameter Name="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <ElementType Name="getNoticeByPageResult">
      <Column Name="rowNum" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="notice_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="empolyee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="publish_time" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getNoticePageCount" Method="getNoticePageCount" IsComposable="true">
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getTaxiByOwnerEmpolyeeId" Method="getTaxiByOwnerEmpolyeeId" IsComposable="true">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="getTaxiByOwnerEmpolyeeIdResult">
      <Column Name="plate_number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="taxi_color" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="taxi_brand" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="is_available" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="owner_firm_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="owner_empolyee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getTaxiByPlateNumber" Method="getTaxiByPlateNumber" IsComposable="true">
    <Parameter Name="plate_number" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="getTaxiByPlateNumberResult">
      <Column Name="taxi_color" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="taxi_brand" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="is_available" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="owner_empolyee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_card" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="photo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="firm_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firm_name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="empolyee_address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="firm_address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="plate_number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getTaxiHostInformation" Method="getTaxiHostInformation" IsComposable="true">
    <ElementType Name="getTaxiHostInformationResult">
      <Column Name="plate_number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="taxi_color" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="taxi_brand" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="is_available" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="owner_empolyee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_card" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="photo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="firm_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firm_name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="empolyee_address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="firm_address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.isDriver" Method="isDriver" IsComposable="true">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.isEmpolyee" Method="isEmpolyee" IsComposable="true">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.isHost" Method="isHost" IsComposable="true">
    <Parameter Name="empolyee_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>